#!/usr/bin/perl

my @a = 
(
'UTOTRAKK', 'ALLY FINANCIAL', 'BAY ENTERPRISE GROUP', 'BHFC', 'C & F FINANCE', 'CARMAX AUTO FINANCE', 'CFAM', 'CHRYSLER CAPITAL-2', 'CHRYSLER CAPITAL-3', 'CITY WIDE INVESTIGATIONS', 'CLA', 'CONSUMER PORTFOLIO', 'EXETER', 'FORD MOTOR CREDIT', 'HYUNDAI MOTOR FINANCE', 'NISSAN MOTOR ACCEPTANCE ', 'NMAC LOSS RECOVERY IGS', 'SAFCO', 'SANTANDER-1', 'SANTANDER-2', 'SANTANDER-3', 'VW CREDIT-PSC', 'VW CREDIT-CSC', 'WELLS FARGO', 'WESTLAKE FINANCIAL', 'UNIVERSAL ACCEPTANCE CORP', 'TURBO TITLE LOANS', 'PRA RECEIVABLE MANAGEMENT', 'SANTANDER-4', 'PRA RECEIVABLES', 'CHRYSLER CAPITAL-1', 'VW CREDIT', 'SST',
'AARON BRAZIL', 'AARON STEELE', 'ADAM CUTHBERTSON', 'AIMEE LAMOUREUX', 'ALEXANDRIA VELIS', 'ALEXIS SMITH', 'ANTHONY D\'LALLO','BRANDICE PLUNKETT','BRANDON BURKHOUSE','BRIAN SHULTIS','BRYAN OLSON','CASEY FLISSINGER','CHARLES RUTH','CHERYL STUCKEY','CHRISTY GALLOW','COURTNEY KULIK','DAK BROWN','DENISE PRIANO','DEVIN HUGHES','ERICA FARLEY','ERIKA HOLIDAY','HOUSE','JANETTE BAILEY','JASON ANDERSON ','JEREMY LYNCH ','JESSICA WESTPHAL','JINETTE HERNANDEZ','JOHANNA JOHNSON','KESHIA FISHER','KEVIN ZWAHLEN','KATIE HALLING','KRISTINA KARAVAN','KYLE BAUGHER','MADISON POST','MARY SYDLOSKI','NICOLE SEEVERS','NICOLE HO','OLIVER SHIPP','PATRICK MCDONNELL','PRISCILLA NAVA ','RACHEL FADER','RICKLENE SMITH','ROGER GOSS','ROLF BELL','ROSE CUELLAR','SARAH BLANKENSHIP','SEAN SASVILLE','SHAUNA HARRIS','SHAY HARMON','STACY FISHER','STEVE ESTEY','TATYANA NESTEROVA','THOMAS ANDERSON ','TIMOTHY BEEMAN','TONY QUADRA','TONIA GATTO','TRAVIS RUDNICK','TREY JACKSON','ZAC BASTIEN'
);

s/(?<=\w)(.)/\l$1/g for @a;

print join "\n", @a;
